/*
 * This source file was generated by the Gradle 'init' task
 */
package advent.of.code.day01;

public class Day01 {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Day01().getGreeting());
    }
}
