/*
 * This source file was generated by the Gradle 'init' task
 */
package advent.of.code.day00;

public class Day00 {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Day00().getGreeting());
    }
}
