/*
 * This source file was generated by the Gradle 'init' task
 */
package advent.of.code;

import org.junit.jupiter.api.Test;

import advent.of.code.day00.Day00;

import static org.junit.jupiter.api.Assertions.*;

class Day00Test {
    @Test void appHasAGreeting() {
        Day00 classUnderTest = new Day00();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
