/*
 * This source file was generated by the Gradle 'init' task
 */
package advent.of.code;

import org.junit.jupiter.api.Test;

import advent.of.code.day01.Day01;

import static org.junit.jupiter.api.Assertions.*;

class Day01Test {
    @Test
    void day01_exampleA() {
        Day01 classUnderTest = new Day01();
        assertEquals(3, classUnderTest.solvePartA("example01.txt"));
    }

    @Test
    void day01_inputA() {
        Day01 classUnderTest = new Day01();
        assertEquals(1191, classUnderTest.solvePartA("day01.txt"));
    }

    @Test
    void day01_exampleB() {
        Day01 classUnderTest = new Day01();
        assertEquals(6, classUnderTest.solvePartB("example01.txt"));
    }

    @Test
    void day01_inputB() {
        Day01 classUnderTest = new Day01();
        // assertEquals(2404, classUnderTest.solvePartB("day01.txt"));
        assertEquals(6858, classUnderTest.solvePartB("day01.txt"));
    }
}
